extends:
  - stylelint-config-recommended
  - stylelint-config-standard-scss
rules:
  at-rule-no-unknown: null
  no-descending-specificity: null
  selector-type-no-unknown: null
  selector-class-pattern: null
