import './modules/init.js'
import './modules/application.js'
import './modules/execution.js'
import './modules/receipt_controller.js'
import './modules/invoices_controller.js'
import './modules/indicators_controller.js'
