#!/bin/bash
set -e
sleep 5
while [ ! $(grep -m 1 -o 'admin.js' /gobierto/public/packs/manifest.json) ]
do
    sleep 5
done
echo -e "\e[92mDeploy Application\e[39m"
$PWD/bin/rails s -b 0.0.0.0 -p 3000 -e $RAILS_ENV