export const categoryTitleEng = [
  "agriculture",
  "architecture",
  "audiovisual",
  "catering",
  "construction",
  "culture",
  "education",
  "electrical",
  "environment",
  "finance",
  "furniture",
  "health",
  "industry",
  "legal",
  "other",
  "print",
  "security",
  "social_services",
  "software",
  "telecom",
  "textile",
  "transportation"
]

export const categoryTitlesCat = [
  "Serveis agrícoles i forestals",
  "Arquitectura i enginyeria",
  "Audiovisual",
  "Hostaleria i restauració",
  "Construcció i manteniment",
  "Cultura i esport",
  "Ensenyament i formació",
  "Equips elèctrics i d 'il·luminació",
  "Medi ambient",
  "Serveis financers i assegurances",
  "Mobiliari",
  "Salut",
  "Indústria i maquinària",
  "Jurídic, comptabilitat, màrqueting...",
  "Altres",
  "Impressió i material d 'oficina",
  "Seguretat",
  "Serveis socials",
  "Consultoria i desenvolupament de programari, equips i llicències",
  "Telecomunicacions i correus",
  "Tèxtil",
  "Transport"
]

export const categoryTitlesEsp = [
  "Servicios agrícolas y forestales",
  "Arquitectura e ingeniería",
  "Audiovisual",
  "Hostelería y restauración",
  "Construcción y mantenimiento",
  "Cultura y deporte",
  "Enseñanza y formación",
  "Equipos eléctricos y de iluminación",
  "Medio ambiente",
  "Servicios financieros y seguros",
  "Mobiliario",
  "Salud",
  "Industria y maquinaria",
  "Jurídico, contabilidad, mercadotecnia...",
  "Otros",
  "Impresión y material de oficina",
  "Seguridad",
  "Servicios sociales",
  "Consultoría y desarrollo de software, equipos y licencias",
  "Telecomunicaciones y correos",
  "Textil",
  "Transporte"
]
