---
default: &defaults
  name: "Gobierto"
  # Supports ERB
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  ignore_errors:
    - SystemExit
    - ActionController::InvalidCrossOriginRequest
    - ActionController::RoutingError
    - ActionController::UnknownFormat
  enable_frontend_error_catching: true
  enable_gc_instrumentation: true
  ignore_actions:
    - "GobiertoPeople::People::PersonEventsController#index"
    - "GobiertoPeople::PersonEventsController#index"
    - "GobiertoPeople::PastPersonEventsController#index"
    - "GobiertoPeople::People::PastPersonEventsController#index"
    - "GobiertoPeople::People::PersonEventsController#show"
    - "GobiertoPeople::GovernmentPartyPastPersonEventsController#index"

development:
  <<: *defaults
  active: true

test:
  <<: *defaults
  active: false

staging:
  <<: *defaults
  revision: "<%= `[ -f REVISION ] && cat REVISION`.strip %>"
  active: true
  ignore_namespaces:
    - background_job
    - background
    - ignore_on_appsignal

production:
  <<: *defaults
  active: true
  revision: "<%= `[ -f REVISION ] && cat REVISION`.strip %>"
  ignore_namespaces:
    - background_job
    - background
    - ignore_on_appsignal
