default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  elastic_url: <%= ENV.fetch("ELASTICSEARCH_URL") { "http://localhost:9200" } %>
  google_places_api_key: <%= ENV["GOOGLE_PLACES_API_KEY"] %>
  google_maps_geocoding_api_key: <%= ENV["GOOGLE_MAPS_GEOCODING_API_KEY"] %>
  mailer_delivery_method: <%= ENV["MAILER_DELIVERY_METHOD"] %>
  mailer_smtp_settings:
    address: <%= ENV["MAILER_SMTP_ADDRESS"] %>
    user_name: <%= ENV["MAILER_SMTP_USER_NAME"] %>
    password: <%= ENV["MAILER_SMTP_PASSWORD"] %>
    port: <%= ENV["MAILER_SMTP_PORT"] %>
    authentication: <%= ENV["MAILER_SMTP_AUTHENTICATION"] %>
    enable_starttls_auto: <%= ActiveModel::Type::Boolean.new.cast(ENV["MAILER_SMTP_ENABLE_STARTTLS_AUTO"] || false) %>
    domain: <%= ENV["MAILER_SMTP_DOMAIN"] %>
    openssl_verify_mode: <%= ENV["MAILER_SMTP_OPENSSL_VERIFY_MODE"] %>
  asymmetric_encryption_key: <%= ENV["ASYMMETRIC_ENCRYPTION_KEY"] %>
  sidekiq_web_usr: <%= ENV["SIDEKIQ_WEB_USR"] %>
  sidekiq_web_pwd: <%= ENV["SIDEKIQ_WEB_PWD"] %>
  preset_admin_password: <%= ENV["PRESET_ADMIN_PASSWORD"] %>
  rollbar_access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  rollbar_post_client_item: <%= ENV["ROLLBAR_POST_CLIENT_ITEM"] %>

development:
  <<: *default
  secret_key_base: df4941e22796fac2458f93729b3f95680aecc74e6a6fcc5ba0b3714ebbeb2a7099acb714a33b7de87bcd8e2b75ad04c624856a496649c42b33e336071a5f6aa3

test:
  <<: *default
  secret_key_base: 074ecf44262876b32f0547beaff25b9f165719f11191392026335cef9488b3e67600ce476e3060fb57c48d5797fa9fb8e1629ea434fb09e21520cba8f1974c8e

staging:
  <<: *default

production:
  <<: *default
