#!/bin/sh

# Setup custom engine 1
git clone git@github.com:PopulateTools/$CUSTOM_ENGINE_NAME_1.git ~/$CUSTOM_ENGINE_NAME_1
cd ~/$CUSTOM_ENGINE_NAME_1
./script/setup.sh
./script/create_webpacker_symlinks.sh
