#!/bin/sh

bundle exec rails gobierto_budgets:elastic_search_schemas:manage:reset
bundle exec rails gobierto_budgets:elastic_search_schemas:manage:create
bundle exec rails gobierto_budgets:fixtures:load
bundle exec rails test
