#!/bin/sh

bundle exec rails gobierto_budgets:elasticsearch:drop_indices
bundle exec rails gobierto_budgets:elasticsearch:create_indices
bundle exec rails gobierto_budgets:fixtures:load
bundle exec rails test
