// import '../../assets/stylesheets/gobierto-user.scss'
import './modules/init.js'
import './modules/application.js'
import './modules/user_registration_controller.js'
import './modules/user_subscription_preferences_controller.js'
